css_locator_1: str = "a.header_logo"
css_locator_2: str = "a[class='btn header-link -active']"
css_locator_3: str = "button[appscrollto='aboutSection']"
css_locator_4: str = "button[appscrollto='contactsSection']"
css_locator_5: str = "div>button[class='btn btn-outline-white header_signin']"
css_locator_6: str = "section[class='section hero']"
css_locator_7: str = "div[class='section about']"
css_locator_8: str = "div[class='section contacts']"
css_locator_9: str = "button[class$='btn-primary']"
css_locator_10: str = "*[class^='hero']"
css_locator_11: str = "span[class$='facebook']"
css_locator_12: str = "span[class$='telegram']"
css_locator_13: str = "span[class$='youtube']"
css_locator_14: str = "span[class$='instagram']"
css_locator_15: str = "span[class$='linkedin']"