xpath_locator_1: str = ".//a[@class='header_logo']"
xpath_locator_2: str = ".//a[text()='Home']"
xpath_locator_3: str = ".//button[text()='About']"
xpath_locator_4: str = ".//button[text()='Contacts']"
xpath_locator_5: str = ".//button[text()='Sign In']"
xpath_locator_6: str = ".//section"
xpath_locator_7: str = ".//div[@class='section about']"
xpath_locator_8: str = ".//div[@class='section contacts']"
xpath_locator_9: str = ".//button[text()='Sign up']"
xpath_locator_10: str = ".//*[contains(@class, 'hero')]"
xpath_locator_11: str = ".//span[contains(@class, 'facebook')]"
xpath_locator_12: str = ".//span[contains(@class, 'telegram')]"
xpath_locator_13: str = ".//span[contains(@class, 'youtube')]"
xpath_locator_14: str = ".//span[contains(@class, 'instagram')]"
xpath_locator_15: str = ".//span[contains(@class, 'linkedin')]"
xpath_locator_16: str = ".//a[text()='ithillel.ua']"
xpath_locator_17: str = ".//a[text()='support@ithillel.ua']"
xpath_locator_18: str = ".//a[text()='ithillel.ua']/.."
xpath_locator_19: str = ".//img[@alt='Instructions' and contains(@src, 'info_1.jpg')]"
xpath_locator_20: str = ".//img[@alt='Instructions' and contains(@src, 'info_2.jpg')]"
xpath_locator_21: str = ".//img[@alt='Instructions']"
xpath_locator_22: str = ".//p[text()='Log fuel expenses']"
xpath_locator_23: str = ".//button[text()='Guest log in']"
xpath_locator_24: str = ".//div[@id='movie_player']"
xpath_locator_25: str = ".//a[@class='footer_logo']"